Update logs

diff --git a/bin/vscodeenv-darwin b/bin/vscodeenv-darwin
--- a/bin/vscodeenv-darwin
+++ b/bin/vscodeenv-darwin
@@ -4,25 +4,26 @@ set -eu
 export IFS=$'\n\t'
 export LC_ALL=C
 
-# export for func
-[ "${LOG_COLOR:-}" = false ] || export enablecolor=true
-export  pipe_debug="awk \"{print \\\"${enablecolor:+\\\\033[0;34m}\$(date +%Y-%m-%dT%H:%M:%S%z) [ debug] \\\"\\\$0\\\"${enablecolor:+\\\\033[0m}\\\"}\" /dev/stdin"
-export   pipe_info="awk \"{print \\\"${enablecolor:+\\\\033[0;32m}\$(date +%Y-%m-%dT%H:%M:%S%z) [  info] \\\"\\\$0\\\"${enablecolor:+\\\\033[0m}\\\"}\" /dev/stdin"
-export pipe_notice="awk \"{print \\\"${enablecolor:+\\\\033[0;36m}\$(date +%Y-%m-%dT%H:%M:%S%z) [notice] \\\"\\\$0\\\"${enablecolor:+\\\\033[0m}\\\"}\" /dev/stdin"
-export   pipe_warn="awk \"{print \\\"${enablecolor:+\\\\033[0;33m}\$(date +%Y-%m-%dT%H:%M:%S%z) [  warn] \\\"\\\$0\\\"${enablecolor:+\\\\033[0m}\\\"}\" /dev/stdin"
-export  pipe_error="awk \"{print \\\"${enablecolor:+\\\\033[0;31m}\$(date +%Y-%m-%dT%H:%M:%S%z) [ error] \\\"\\\$0\\\"${enablecolor:+\\\\033[0m}\\\"}\" /dev/stdin"
-export   pipe_crit="awk \"{print \\\"${enablecolor:+\\\\033[1;31m}\$(date +%Y-%m-%dT%H:%M:%S%z) [  crit] \\\"\\\$0\\\"${enablecolor:+\\\\033[0m}\\\"}\" /dev/stdin"
+# MIT License Copyright (c) 2021 ginokent https://github.com/rec-logger/rec.sh
+# Common
+_recRFC3339() { date "+%Y-%m-%dT%H:%M:%S%z" | sed "s/\(..\)$/:\1/"; }
+_recCmd() { for a in "$@"; do if echo "${a:-}" | grep -Eq "[[:blank:]]"; then printf "'%s' " "${a:-}"; else printf "%s " "${a:-}"; fi; done | sed "s/ $//"; }
+# Color
+RecDefault() { test "  ${REC_SEVERITY:-0}" -gt 000 2>/dev/null || echo "$*" | awk "{print   \"$(_recRFC3339) [\\033[0;35m  DEFAULT\\033[0m] \"\$0\"\"}" 1>&2; }
+RecDebug() { test "    ${REC_SEVERITY:-0}" -gt 100 2>/dev/null || echo "$*" | awk "{print   \"$(_recRFC3339) [\\033[0;34m    DEBUG\\033[0m] \"\$0\"\"}" 1>&2; }
+RecInfo() { test "     ${REC_SEVERITY:-0}" -gt 200 2>/dev/null || echo "$*" | awk "{print   \"$(_recRFC3339) [\\033[0;32m     INFO\\033[0m] \"\$0\"\"}" 1>&2; }
+RecNotice() { test "   ${REC_SEVERITY:-0}" -gt 300 2>/dev/null || echo "$*" | awk "{print   \"$(_recRFC3339) [\\033[0;36m   NOTICE\\033[0m] \"\$0\"\"}" 1>&2; }
+RecWarning() { test "  ${REC_SEVERITY:-0}" -gt 400 2>/dev/null || echo "$*" | awk "{print   \"$(_recRFC3339) [\\033[0;33m  WARNING\\033[0m] \"\$0\"\"}" 1>&2; }
+RecError() { test "    ${REC_SEVERITY:-0}" -gt 500 2>/dev/null || echo "$*" | awk "{print   \"$(_recRFC3339) [\\033[0;31m    ERROR\\033[0m] \"\$0\"\"}" 1>&2; }
+RecCritical() { test " ${REC_SEVERITY:-0}" -gt 600 2>/dev/null || echo "$*" | awk "{print \"$(_recRFC3339) [\\033[0;1;31m CRITICAL\\033[0m] \"\$0\"\"}" 1>&2; }
+RecAlert() { test "    ${REC_SEVERITY:-0}" -gt 700 2>/dev/null || echo "$*" | awk "{print   \"$(_recRFC3339) [\\033[0;41m    ALERT\\033[0m] \"\$0\"\"}" 1>&2; }
+RecEmergency() { test "${REC_SEVERITY:-0}" -gt 800 2>/dev/null || echo "$*" | awk "{print \"$(_recRFC3339) [\\033[0;1;41mEMERGENCY\\033[0m] \"\$0\"\"}" 1>&2; }
+RecExec() { RecInfo "$ $(_recCmd "$@")" && "$@"; }
+RecRun() { _dlm="####R#E#C#D#E#L#I#M#I#T#E#R####" _all=$({ _out=$("$@") && _rtn=$? || _rtn=$? && printf "\n%s" "${_dlm:?}${_out:-}" && return ${_rtn:-0}; } 2>&1) && _rtn=$? || _rtn=$? && _dlmno=$(echo "${_all:-}" | sed -n "/${_dlm:?}/=") && _cmd=$(_recCmd "$@") && _stdout=$(echo "${_all:-}" | tail -n +"${_dlmno:-1}" | sed "s/^${_dlm:?}//") && _stderr=$(echo "${_all:-}" | head -n "${_dlmno:-1}" | grep -v "^${_dlm:?}") && RecInfo "$ ${_cmd:-}" && { [ -z "${_stdout:-}" ] || RecInfo "${_stdout:?}"; } && { [ -z "${_stderr:-}" ] || RecWarning "${_stderr:?}"; } && return ${_rtn:-0}; }
+# export functions for bash
+# shellcheck disable=SC3045
+echo "${SHELL-}" | grep -q bash$ && export -f _recRFC3339 _recCmd RecDefault RecDebug RecInfo RecWarning RecError RecCritical RecAlert RecEmergency RecExec RecRun
 
-# func
-export severity="${LOG_SEVERITY:--1}"
-Debugln  () { [ "${severity:--1}" -gt 100 ] 2>/dev/null || echo "$*" | bash -c "${pipe_debug:?}"  1>&2; }
-Infoln   () { [ "${severity:--1}" -gt 200 ] 2>/dev/null || echo "$*" | bash -c "${pipe_info:?}"   1>&2; }
-Noticeln () { [ "${severity:--1}" -gt 300 ] 2>/dev/null || echo "$*" | bash -c "${pipe_notice:?}" 1>&2; }
-Warnln   () { [ "${severity:--1}" -gt 400 ] 2>/dev/null || echo "$*" | bash -c "${pipe_warn:?}"   1>&2; }
-Errorln  () { [ "${severity:--1}" -gt 500 ] 2>/dev/null || echo "$*" | bash -c "${pipe_error:?}"  1>&2; }
-Critln   () { [ "${severity:--1}" -gt 600 ] 2>/dev/null || echo "$*" | bash -c "${pipe_crit:?}"   1>&2; }
-Run      () { Debugln "$ $(s=" "; i=1; for a in "$@"; do if [ $i = $# ]; then s=""; fi; if echo "$a" | grep -Eq "[[:blank:]]"; then printf "'%s'$s" "$a"; else printf "%s$s" "$a"; fi; done;)"; "$@"; }
-Catch    () { err=$?; rm -rf "${HOME_TMP_DIR:-/tmp/${PROG_NAME:?}/no/such/file/or/directory}"; Errorln "exit ${err-}"; return ${err-}; } && trap Catch ERR
 CommandNotFound () { ! command -v "${1:?"CommandNotFound: \$1 as command is required"}" >/dev/null; }
 
 # const
@@ -46,7 +47,7 @@ APPLICATIONS="/Applications"
 VISUAL_STUDIO_CODE_APP="${VISUAL_STUDIO_CODE:?}.app"
 APPLICATIONS_VISUAL_STUDIO_CODE_APP="${APPLICATIONS:?}/${VISUAL_STUDIO_CODE_APP:?}"
 CODE_EXE="${APPLICATIONS_VISUAL_STUDIO_CODE_APP:?}/Contents/Resources/app/bin/code"
-CODE_EXE_SYMBOLIC_LINK="/usr/local/bin/code"
+CODE_EXE_SYMBOLIC_LINK=${CODE_PATH:="~/bin/code"}
 
 # var
 grep_cond_not_found_versions=$(i=0; for version in "${NOT_FOUND_VERSIONS[@]}"; do i=$((i+1)); echo -n "${version:?}"; [[ $i -ge ${#NOT_FOUND_VERSIONS[@]} ]] || echo -n "|"; done;)  # NOTE: like this: "0.10.1|0.10.6|1.7.0"
@@ -56,14 +57,14 @@ url_list=""
 __checkOS () {
   os=$(uname -s | tr "[:upper:]" "[:lower:]")
   if [[ ${os:=null} != "${OS:?}" ]] ;then
-    Errorln "This OS is not supported: ${os:?}"
+    RecError "This OS is not supported: ${os:?}"
     exit 1
   fi
 }
 
 __commandRequired () {
   if CommandNotFound "${1:?}"; then
-    Errorln "'${1:?}' is required"
+    RecError "'${1:?}' is required"
     exit 1
   fi
 }
@@ -125,16 +126,16 @@ __wget () {
   source_url="${1:?}"
   destination_path="${2:?}"
   shift && shift
-  Infoln "download ${source_url:?} -> ${destination_path:?}"
-  Run wget "${source_url:?}" --output-document="${destination_path:?}" "$@"
+  RecInfo "download ${source_url:?} -> ${destination_path:?}"
+  RecExec wget "${source_url:?}" --output-document="${destination_path:?}" "$@"
 }
 
 __unzipWithResetTmpDir () {
   zip_path="${1:?}"
   unzip_tmp_path="${2:?}"
   __resetTmpDir "${unzip_tmp_path:?}"
-  Infoln "unzip '${zip_path:?}' -> '${unzip_tmp_path:?}/${VISUAL_STUDIO_CODE_APP:?}'"
-  Run unzip -q -o "${zip_path:?}" -d "${unzip_tmp_path:?}" "${VISUAL_STUDIO_CODE_APP:?}/*"
+  RecInfo "unzip '${zip_path:?}' -> '${unzip_tmp_path:?}/${VISUAL_STUDIO_CODE_APP:?}'"
+  RecExec unzip -q -o "${zip_path:?}" -d "${unzip_tmp_path:?}" "${VISUAL_STUDIO_CODE_APP:?}/*"
 }
 
 __mustGetVersion () {
@@ -149,11 +150,11 @@ __mustGetVersion () {
   if __getVersionList | grep -E "^${version-}$" >/dev/null; then
     echo "${version:?}"
   elif [[ -n ${version-} ]]; then
-    Errorln "version not found: ${version-}"
-    Errorln "check the available versions: $0 list"
+    RecError "version not found: ${version-}"
+    RecError "check the available versions: $0 list"
     exit 1
   else
-    Noticeln "no version was specified. use latest version"
+    RecNotice "no version was specified. use latest version"
     __getLatestVersion
   fi
 }
@@ -164,22 +165,22 @@ __mustGetSpecificVersionURL () {
   if [[ "${url-}" ]]; then
     echo "${url:?}"
   else
-    Errorln "version not found: ${version-}"
-    Errorln "check the available versions: $0 list"
+    RecError "version not found: ${version-}"
+    RecError "check the available versions: $0 list"
     exit 1
   fi
 }
 
 __createCodeBinSymbolicLink () {
   if [[ -f "${CODE_EXE:?}" ]]; then
-    if [[ ! -L ${CODE_EXE_SYMBOLIC_LINK:?} ]] && [[ ! -f ${CODE_EXE_SYMBOLIC_LINK:?} ]]; then
-      Infoln "create symblic link '${CODE_EXE:?}' -> '${CODE_EXE_SYMBOLIC_LINK:?}'"
-      Run ln -sf "${CODE_EXE:?}" "${CODE_EXE_SYMBOLIC_LINK:?}"
+    if ! command -v code 1>/dev/null && [[ ! -L ${CODE_EXE_SYMBOLIC_LINK:?} ]] && [[ ! -f ${CODE_EXE_SYMBOLIC_LINK:?} ]]; then
+      RecInfo "create symblic link '${CODE_EXE:?}' -> '${CODE_EXE_SYMBOLIC_LINK:?}'"
+      RecExec ln -sf "${CODE_EXE:?}" "${CODE_EXE_SYMBOLIC_LINK:?}"
     elif [[ $(wc -c < "${CODE_EXE:?}") -eq $(wc -c < "${CODE_EXE_SYMBOLIC_LINK:?}") ]]; then
       # If '/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code' size == '/usr/local/bin/code' size
       return 0
     else
-      Warnln "'${CODE_EXE_SYMBOLIC_LINK:?}' already exists"
+      RecWarning "'${CODE_EXE_SYMBOLIC_LINK:?}' already exists"
     fi
   fi
 }
@@ -191,13 +192,13 @@ __existsApplicationsVisualStudioCodeApp () {
 
 
 __launch () {
-  Infoln "launch '${APPLICATIONS_VISUAL_STUDIO_CODE_APP:?}'"
-  Run open -a "${APPLICATIONS_VISUAL_STUDIO_CODE_APP:?}"
+  RecInfo "launch '${APPLICATIONS_VISUAL_STUDIO_CODE_APP:?}'"
+  RecExec open -a "${APPLICATIONS_VISUAL_STUDIO_CODE_APP:?}"
 }
 
 __currentVersionExit0 () {
-  Infoln "current version"
-  Run "${CODE_EXE:?}" --version || true
+  RecInfo "current version"
+  RecExec "${CODE_EXE:?}" --version || true
 }
 
 __hasOptionListExtensions () {
@@ -258,14 +259,14 @@ __install () {
   source_url=$(__mustGetSpecificVersionURL "${version:?}")
   destination_path=$(__getZipDestinationPath "${version:?}")
 
-  Infoln "install '${VISUAL_STUDIO_CODE_APP:?}' version ${version:?}"
+  RecInfo "install '${VISUAL_STUDIO_CODE_APP:?}' version ${version:?}"
 
   if __existsApplicationsVisualStudioCodeApp; then
-    Warnln "'${APPLICATIONS_VISUAL_STUDIO_CODE_APP:?}' already installed"
+    RecWarning "'${APPLICATIONS_VISUAL_STUDIO_CODE_APP:?}' already installed"
     __currentVersionExit0
     if ! [[ $* =~ (^|.*[^[:graph:]]+)(-f|--force)([^[:graph:]]+.*|$) ]]; then
       # If force option is false,
-      Noticeln "If you want to overwrite install, use '--force' option"
+      RecNotice "If you want to overwrite install, use '--force' option"
       return 0
     fi
   fi
@@ -273,11 +274,11 @@ __install () {
   # download and unzip
   __wget "${source_url:?}" "${destination_path:?}" --continue
   if ! __unzipWithResetTmpDir "${destination_path:?}" "${HOME_TMP_DIR:?}"; then
-    Warnln "failed to unzip ${destination_path:?}, retry to download ${source_url:?}"
+    RecWarning "failed to unzip ${destination_path:?}, retry to download ${source_url:?}"
     # retry once "wget" without "--continue" option
     __wget "${source_url:?}" "${destination_path:?}"
     if ! __unzipWithResetTmpDir "${destination_path:?}" "${HOME_TMP_DIR:?}"; then
-      Errorln "failed to unzip ${destination_path:?}"
+      RecError "failed to unzip ${destination_path:?}"
       exit 1
     fi
   fi
@@ -285,13 +286,13 @@ __install () {
   # backup
   if __existsApplicationsVisualStudioCodeApp; then
     __resetTmpDir "${BACKUP_DIR:?}"
-    Infoln "backup '${APPLICATIONS_VISUAL_STUDIO_CODE_APP:?}' -> ${BACKUP_DIR:?}"
-    Run mv "${APPLICATIONS_VISUAL_STUDIO_CODE_APP:?}" "${BACKUP_DIR:?}"
+    RecInfo "backup '${APPLICATIONS_VISUAL_STUDIO_CODE_APP:?}' -> ${BACKUP_DIR:?}"
+    RecExec mv "${APPLICATIONS_VISUAL_STUDIO_CODE_APP:?}" "${BACKUP_DIR:?}"
   fi
 
   # mv
-  Infoln "install '${HOME_TMP_DIR:?}/${APPLICATIONS_VISUAL_STUDIO_CODE_APP:?}' -> '${APPLICATIONS_VISUAL_STUDIO_CODE_APP:?}'"
-  Run mv "${HOME_TMP_DIR:?}/${VISUAL_STUDIO_CODE_APP:?}" "${APPLICATIONS_VISUAL_STUDIO_CODE_APP:?}"
+  RecInfo "install '${HOME_TMP_DIR:?}/${APPLICATIONS_VISUAL_STUDIO_CODE_APP:?}' -> '${APPLICATIONS_VISUAL_STUDIO_CODE_APP:?}'"
+  RecExec mv "${HOME_TMP_DIR:?}/${VISUAL_STUDIO_CODE_APP:?}" "${APPLICATIONS_VISUAL_STUDIO_CODE_APP:?}"
 
   # ln -s
   __createCodeBinSymbolicLink
@@ -309,14 +310,14 @@ __list () {
 }
 
 __kill () {
-  Run bash -c "pgrep -f \"${APPLICATIONS_VISUAL_STUDIO_CODE_APP:?}\" | xargs kill"
+  RecExec bash -c "pgrep -f \"${APPLICATIONS_VISUAL_STUDIO_CODE_APP:?}\" | xargs kill"
 }
 
 __selfUpdate () {
-  Infoln "self update"
+  RecInfo "self update"
   cmd="wget \"${SELF_UPDATE_URL:?}\" --output-document=\"${UPDATE_DL_TMP:?}\"; chmod -v +x \"${UPDATE_DL_TMP:?}\"; mv \"${UPDATE_DL_TMP:?}\" \"$0\""
-  if [[ -w $0 ]] || { [[ -w $(dirname "$0") ]] && [[ ! -e $0 ]]; }; then Run bash -c "${cmd:?}"; else Run sudo -u root bash -c "${cmd:?}"; fi
-  Infoln "updated"
+  if [[ -w $0 ]] || { [[ -w $(dirname "$0") ]] && [[ ! -e $0 ]]; }; then RecExec bash -c "${cmd:?}"; else RecExec sudo -u root bash -c "${cmd:?}"; fi
+  RecInfo "updated"
 }
 
 __usage () {
